baseURL = "http://example.org/"
languageCode = "en-us"
title = "Samkové umelecké diela"
theme = "newsroom"
# googleAnalytics = "UA-167869327-1"
enableRobotsTXT = true
	
[params]
# favicon = "/images/fav.png"
    email = "samko.cajkovic@gmail.com"
    location = "Vinicne, Slovensko"
    # locale = "en_US"
    # ga_analytics = "" # google analytics ID e.g UA-116386578-1
    # ga_verify = "" # google verification code e.g 5jb-rxeBfITeJQKOuUss3ud6FPGTxXkCho-ZN5qlrZg
    # twitter = "" # twitter handle e.g @weru
    # mainSections = ["blog", "docs"] see https://gohugo.io/functions/where/#mainsections
    # uncomment the line below will disable darkmode by default.
    # uncomment and set value below to either "light" or "dark" to make default mode dark.
    defaultMode = "light" # Note that the UI control for toggling darkmode will remain in place. This way, the user can decide which mode they would like to use while browsing your website
    logo = "" # if the value is an empty string, the site title will be shown instead
    faviconsDir = "images/icons/" # with a trailing slash
    blogDir = "post" # edit


[markup]
  [markup.goldmark.renderer]
    hardWraps = false
    unsafe = false # change to true to enable inclusion of rawHTML and math functions
    xhtml = false
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = false
    tabWidth = 2

# [deployment]
# [[deployment.targets]]
# name = "s3-deployment"

# S3; see https://gocloud.dev/howto/blob/#s3
# For S3-compatible endpoints, see https://gocloud.dev/howto/blob/#s3-compatible
# URL = "s3://samko-portfolio-311008325132?region=eu-west-1"